[env:genericSTM32F103C8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = hid
extra_scripts = pre:scripts/version_info.py
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D SERIAL_RX_BUFFER_SIZE=512
  -D SERIAL_TX_BUFFER_SIZE=256
monitor_speed = 115200
build_src_filter =
  +<*>
  -<line_crc_echo_main.cpp>

[env:line_crc_echo]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = hid
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D SERIAL_RX_BUFFER_SIZE=512
  -D SERIAL_TX_BUFFER_SIZE=256
monitor_speed = 115200
build_src_filter =
  +<line_crc_echo_main.cpp>
