[env:genericSTM32F103C8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = hid
extra_scripts = pre:scripts/version_info.py
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
monitor_speed = 115200
