name: firmware-ci

on:
  push:
    paths:
    - "FlashBangFirmware/**"
    - ".github/workflows/firmware-ci.yml"
  pull_request:
    paths:
    - "FlashBangFirmware/**"
    - ".github/workflows/firmware-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FlashBangFirmware
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: pip install platformio

    - name: Build
      run: pio run
